context = """
    This are the tables in the database and their columns:
    
    TABLE `sis_tipo_grupo_conciliaciones` (
    `id_grupo_conciliaciones_pk` int NOT NULL AUTO_INCREMENT,
    `id_cuenta` int DEFAULT NULL,
    `desc_nombre_grupo` varchar(100) DEFAULT NULL,
    `desc_grupo_conciliaciones` varchar(100) DEFAULT NULL,
    `desc_label_corta_grupo` varchar(20) DEFAULT NULL,
    `num_identificacion_grupo` int DEFAULT NULL,
    `cod_color_hex` varchar(8) DEFAULT NULL,
    `cod_color_hex_fuente_texto` varchar(8) DEFAULT '#ffffff',
    `flag_grupo_default` int DEFAULT NULL,
    `flag_registro_eliminado` int DEFAULT '0',
    `seed_origen_id_grupo_conciliaciones_pk` int DEFAULT NULL,
    PRIMARY KEY (`id_grupo_conciliaciones_pk`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5098 DEFAULT CHARSET=utf8mb3;

    TABLE `sis_cliente` (
    `id_cliente_pk` int NOT NULL AUTO_INCREMENT,
    `fingerprint_cliente` varchar(8) DEFAULT NULL,
    `desc_nombre_empresa_cliente` varchar(100) DEFAULT NULL,
    `desc_dominio_cliente` varchar(45) DEFAULT NULL COMMENT 'Este campo se usa para el login con arroba',
    `razon_social_empresa_cliente` varchar(45) DEFAULT NULL,
    `nom_fantasia_cliente` varchar(100) DEFAULT NULL,
    `RUT` decimal(20,0) DEFAULT NULL,
    `PersonaContacto` varchar(100) DEFAULT NULL,
    `img_logo_cliente` blob,
    `id_pais_empresa_cliente` int DEFAULT NULL,
    `desc_ciudad_empresa_cliente` varchar(100) DEFAULT NULL,
    `desc_direccion_empresa_cliente` varchar(100) DEFAULT NULL,
    `telefono_empresa_cliente` varchar(45) DEFAULT NULL,
    `correo_electronico_empresa_cliente` varchar(100) DEFAULT NULL,
    `id_idioma` int DEFAULT NULL,
    `id_paleta_colores` int DEFAULT NULL,
    `id_theme-borrar` int DEFAULT NULL,
    `timestamp_creacion` datetime DEFAULT NULL,
    `id_usuario_cliente_titular` int DEFAULT NULL,
    `fecha_inicio_operacion` date DEFAULT NULL COMMENT 'Esta fecha define desde cuando es que se generan las fechas posibles para este cliente.\n',
    `cant_licenciamiento_conciliaciones` int DEFAULT NULL,
    `humbral_conciliaciones_bloqueo_procesos` int DEFAULT NULL,
    `flag_cliente_habilitado` int DEFAULT '0',
    `id_cliente_estado` int DEFAULT NULL,
    `id_cliente_plan` int DEFAULT NULL,
    `flag_ldap_enable` int DEFAULT '0',
    `ldap_connection_name` varchar(100) DEFAULT NULL,
    `ldap_url_server` varchar(100) DEFAULT NULL,
    `ldap_username` varchar(100) DEFAULT NULL,
    `ldap_password` varchar(100) DEFAULT NULL,
    `ldap_base_dn` varchar(100) DEFAULT NULL,
    `seg_expiracion_sesion_mins` int DEFAULT '10',
    `seg_largo_minimo_password` int DEFAULT '4',
    `seg_cant_grupos_caracteres_password` int DEFAULT '1',
    `flag_system_client` int DEFAULT '0',
    `flag_seguridad_2fa_activa` int DEFAULT '0',
    `cr_fingerprint` varchar(8) DEFAULT NULL,
    `cr_id_user` int DEFAULT NULL,
    `cr_timestamp` datetime DEFAULT NULL,
    PRIMARY KEY (`id_cliente_pk`)
    ) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb3;

    TABLE `sis_empresas` (
    `ID_Empresa_PK` int NOT NULL AUTO_INCREMENT,
    `id_cliente` int DEFAULT '0',
    `DESC_Empresa` varchar(100) DEFAULT NULL,
    `num_orden` int DEFAULT NULL,
    `ID_Pais` int DEFAULT '0',
    `RazonSocial` varchar(100) DEFAULT NULL,
    `RUT` decimal(20,0) DEFAULT NULL,
    `Direccion` varchar(100) DEFAULT NULL,
    `Telefono` varchar(50) DEFAULT NULL,
    `PersonaContacto` varchar(100) DEFAULT NULL,
    `Email` varchar(100) DEFAULT NULL,
    `ID_SistemaContable` int DEFAULT NULL,
    `ID_TipoCarga` int DEFAULT '0',
    `FLAG_Habilitado` int DEFAULT '1',
    `flag_registro_eliminado` int DEFAULT '0',
    `seed_origen_id_empresa_pk` int DEFAULT NULL,
    `cr_fingerprint` varchar(8) DEFAULT NULL,
    `cr_id_user` int DEFAULT NULL,
    `cr_timestamp` datetime DEFAULT NULL,
    PRIMARY KEY (`ID_Empresa_PK`),
    KEY `fk_sis_empresas@paises_idx` (`ID_Pais`),
    CONSTRAINT `fk_sis_empresas@paises` FOREIGN KEY (`ID_Pais`) REFERENCES `sis_paises` (`ID_Pais_PK`)
    ) ENGINE=InnoDB AUTO_INCREMENT=183 DEFAULT CHARSET=utf8mb3;

    TABLE `dw_movs_entidad` (
    `ID_Fila_PK` int NOT NULL AUTO_INCREMENT,
    `id_cliente` int DEFAULT NULL,
    `ID_Cuenta` int DEFAULT NULL,
    `Cod_AAAAMM` int DEFAULT NULL,
    `cod_fecha_sys` date DEFAULT NULL,
    `Fecha` date DEFAULT '0000-00-00',
    `Descripcion` varchar(255) DEFAULT NULL,
    `Concepto_Nivel2` varchar(255) DEFAULT NULL,
    `NRO_Referencia` bigint DEFAULT NULL,
    `BData_Cod_Referencia_Char` varchar(45) DEFAULT NULL,
    `Val_Debito` decimal(15,2) DEFAULT NULL,
    `Val_Credito` decimal(15,2) DEFAULT NULL,
    `ID_Clasificacion` varchar(5) DEFAULT NULL,
    `FLG_Debe_Haber` int DEFAULT '0',
    `ID_TipoMovimiento` int DEFAULT NULL,
    `Desc_Tipo_Movimiento` varchar(50) DEFAULT NULL,
    `Cod_Matching` int DEFAULT '0',
    `NUM_PasoWorkflow` int DEFAULT NULL,
    `Umbral_Tolerancia` decimal(10,2) DEFAULT NULL,
    `Tolerancia_Ajuste_Matching` decimal(18,2) DEFAULT NULL,
    `flag_conciliado` bit(1) DEFAULT b'0',
    `ID_Cancelacion` int DEFAULT NULL,
    `TimeStamp_Creacion` datetime(3) DEFAULT NULL,
    `ID_User` int DEFAULT NULL,
    `Flag_Error` int DEFAULT '0',
    `Descr_Error` varchar(100) DEFAULT NULL,
    `ctrl_disable_warning` bit(1) DEFAULT b'0',
    `BData_Moneda_Num` int DEFAULT NULL,
    `BData_Moneda_Char` varchar(45) DEFAULT NULL,
    `BData_Importe_SSigno_Decimal` decimal(15,2) DEFAULT NULL,
    `BData_Importe_CSigno_Decimal` decimal(15,2) DEFAULT NULL,
    `BData_Signo_Char` varchar(45) DEFAULT NULL,
    `BData_Debito_Credito_Num` int DEFAULT NULL,
    `BData_Estatus_Movimiento_Num` int DEFAULT NULL,
    `BData_Estatus_Movimiento_Char` varchar(100) DEFAULT '',
    `BData_Tipo_Transaccion_Num` int DEFAULT NULL,
    `BData_Tipo_Transaccion_Char` varchar(45) DEFAULT NULL,
    `BData_Subtipo_Transaccion_Num` int DEFAULT NULL,
    `BData_Subtipo_Transaccion_Char` varchar(45) DEFAULT NULL,
    `BData_Identificador_Unico_Key_Num` bigint DEFAULT NULL,
    `BData_Identificador_Unico_Key_Char` varchar(100) DEFAULT NULL,
    `BData_Empresa_Num` int DEFAULT NULL,
    `BData_Empresa_Char` varchar(45) DEFAULT NULL,
    `BData_Banco_Char` varchar(100) DEFAULT NULL,
    `BData_Empresa_RUT_Num` decimal(20,0) DEFAULT NULL,
    `BData_Empresa_RUT_Char` varchar(100) DEFAULT NULL,
    `BData_Cuenta_Num` decimal(20,0) DEFAULT NULL,
    `BData_Cuenta_Char` varchar(45) DEFAULT NULL,
    `BData_Planilla_Num` int DEFAULT NULL,
    `BData_Sucursal_Num` int DEFAULT NULL,
    `BData_Sucursal_Char` varchar(100) DEFAULT NULL,
    `BData_Departamento_Num` int DEFAULT NULL,
    `BData_Departamento_Char` varchar(100) DEFAULT NULL,
    `BData_Ciudad_Char` varchar(100) CHARACTER SET big5 COLLATE big5_chinese_ci DEFAULT NULL,
    `BData_Localidad_Char` varchar(100) DEFAULT NULL,
    `BData_Sub_Localidad_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Card_Number_Decimal` decimal(45,0) DEFAULT NULL,
    `BData_Tarjet_Card_Number_PCI` varchar(45) DEFAULT NULL,
    `BData_Tarjet_Expiration_Date` varchar(4) DEFAULT NULL,
    `BData_Tarjet_Authorization_Num` bigint DEFAULT NULL,
    `BData_Tarjet_Authorization_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Cant_Cuotas` int DEFAULT NULL,
    `BData_Tarjet_Afiliado_Char` varchar(45) DEFAULT NULL,
    `BData_Tarjet_Tipo_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Marca_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Liquidacion_Num` int DEFAULT NULL,
    `BData_Tarjet_Cupon_Num` decimal(10,0) DEFAULT NULL,
    `BData_Nro_Comercio_Num` decimal(10,0) DEFAULT NULL,
    `BData_Nro_Terminal_Num` decimal(10,0) DEFAULT NULL,
    `BData_Fecha_Compra` date DEFAULT NULL,
    `BData_Fecha_Presentacion` date DEFAULT NULL,
    `BData_Fecha_Liquidacion` date DEFAULT NULL,
    `BData_Fecha_Proceso` date DEFAULT NULL,
    `BData_Voucher_Num` bigint DEFAULT NULL,
    `BData_File_Num` bigint DEFAULT NULL,
    `BData_Medio_Pago_Char` varchar(100) DEFAULT NULL,
    `BData_Canal_Distribucion_Char` varchar(100) DEFAULT NULL,
    `BData_Ciclo_Distribucion_Num` int DEFAULT NULL,
    `BData_Medio_Distribucion_Char` varchar(100) DEFAULT NULL,
    `BData_Ramo_Actividad_Char` varchar(100) DEFAULT NULL,
    `BData_Sector_Actividad_Char` varchar(100) DEFAULT NULL,
    `BData_Cartera_Num` int DEFAULT NULL,
    `BData_Cartera_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Nombre_Char` varchar(200) DEFAULT NULL,
    `BData_Cli_Documento_Char` varchar(45) DEFAULT NULL,
    `BData_Cli_Domicilio_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Correo_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Telefono_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Estatus_Num` int DEFAULT NULL,
    `BData_Cli_Estatus_Char` varchar(100) DEFAULT NULL,
    `BData_Cod_Articulo_Char` varchar(45) DEFAULT NULL,
    `BData_Nombre_Articulo_Char` varchar(50) DEFAULT NULL,
    `BData_Descr_Articulo_Char` varchar(100) DEFAULT NULL,
    `BData_Imp_Credito_Bruto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Debito_Bruto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Credito_Neto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Debito_Neto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Comision` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Margen` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Tasas` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Intercambio` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Bruto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Descuento` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Neto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Factura` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Cashback` decimal(15,2) DEFAULT NULL,
    `VectorExtValor00` decimal(15,2) DEFAULT NULL,
    `VectorExtValor01` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor02` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor03` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor04` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor05` decimal(15,2) DEFAULT NULL,
    `VectorExtValor06` decimal(15,2) DEFAULT NULL,
    `VectorExtValor07` decimal(15,2) DEFAULT NULL,
    `VectorExtValor08` decimal(15,2) DEFAULT NULL,
    `VectorExtValor09` decimal(15,2) DEFAULT NULL,
    `VectorExtValor10` decimal(15,2) DEFAULT NULL,
    `VectorExtTexto01` varchar(100) DEFAULT NULL,
    `VectorExtTexto02` varchar(100) DEFAULT NULL,
    `VectorExtTexto03` varchar(100) DEFAULT NULL,
    `VectorExtTexto04` varchar(100) DEFAULT NULL,
    `VectorExtNum01` int DEFAULT NULL,
    `VectorExtNum02` int DEFAULT NULL,
    `VectorExtNum03` int DEFAULT NULL,
    `VectorExtNum04` int DEFAULT NULL,
    `ID_Template_Formato_Archivo` int DEFAULT NULL,
    `id_sistema_origen` int DEFAULT NULL,
    `cod_sistema_origen_externo` int DEFAULT NULL,
    `Ctrl_Nombre_Archivo_Carga` varchar(200) DEFAULT NULL,
    `id_file_load` int DEFAULT NULL,
    `Ctrl_CheckSum` char(32) DEFAULT NULL,
    `id_clase_movimiento` int DEFAULT '1',
    `id_tipo_estado_partida` int DEFAULT '1',
    `id_movimiento_raiz` bigint DEFAULT NULL,
    `cardinal_descendiente_raiz` int DEFAULT NULL,
    `desc_comentario_movimiento` varchar(200) DEFAULT NULL,
    `flag_caso_asociado` int DEFAULT '0',
    `id_caso_asociado` int DEFAULT NULL,
    PRIMARY KEY (`ID_Fila_PK`),
    KEY `fk_dw_movs_entidad@codmatching_idx` (`Cod_Matching`),
    KEY `fk_dw_movs_entidad@cancelacion_idx` (`ID_Cancelacion`),
    KEY `fk_dw_movs_entidad@cuentas_idx` (`ID_Cuenta`),
    KEY `indice_fecha` (`Fecha`),
    KEY `fk_dw_movs_entidad@cod_aaaamm_idx` (`Cod_AAAAMM`),
    KEY `fk_dw_movs_entidad@flg_dh_idx` (`FLG_Debe_Haber`),
    KEY `index9` (`BData_Identificador_Unico_Key_Num`),
    KEY `tipo_movimiento` (`ID_TipoMovimiento`,`ID_Cuenta`) USING BTREE,
    KEY `index10` (`id_sistema_origen`,`ID_Cuenta`),
    KEY `bdata_cuenta` (`BData_Cuenta_Num`) /*!80000 INVISIBLE */,
    KEY `autorizacion_num` (`BData_Tarjet_Authorization_Num`) /*!80000 INVISIBLE */,
    KEY `autorizacion_char` (`BData_Tarjet_Authorization_Char`),
    KEY `cuenta_num` (`BData_Cuenta_Num`) /*!80000 INVISIBLE */,
    KEY `checksum` (`Ctrl_CheckSum`,`ID_Cuenta`,`Cod_AAAAMM`),
    KEY `Cuenta y Periodo` (`ID_Cuenta`,`Cod_AAAAMM`,`flag_conciliado`),
    CONSTRAINT `fk_dw_movs_entidad@cancelacion` FOREIGN KEY (`ID_Cancelacion`) REFERENCES `dw_cancelaciones` (`ID_Cancelacion_PK`),
    CONSTRAINT `fk_dw_movs_entidad@codmatching` FOREIGN KEY (`Cod_Matching`) REFERENCES `sis_metodo_matching` (`ID_MetodoMatching_PK`),
    CONSTRAINT `fk_dw_movs_entidad@cuentas` FOREIGN KEY (`ID_Cuenta`) REFERENCES `dw_cuentas` (`ID_Cuenta_PK`)
    ) ENGINE=InnoDB AUTO_INCREMENT=14739659 DEFAULT CHARSET=utf8mb3;

    TABLE `dw_movs_contables` (
    `ID_Fila_PK` int NOT NULL AUTO_INCREMENT,
    `id_cliente` int DEFAULT NULL,
    `ID_Cuenta` int DEFAULT NULL,
    `Fecha_Asiento` date DEFAULT '0000-00-00',
    `Cod_AAAAMM` int DEFAULT NULL,
    `cod_fecha_sys` date DEFAULT NULL,
    `Fecha_Maestra` date DEFAULT '0000-00-00',
    `Concepto` varchar(300) DEFAULT NULL,
    `Documento` varchar(50) DEFAULT NULL,
    `Val_Debe` decimal(15,2) DEFAULT NULL,
    `Val_Haber` decimal(15,2) DEFAULT NULL,
    `Nro_Transaccion_Origen` bigint DEFAULT NULL,
    `Nro_Identificacion_Unico` bigint DEFAULT NULL,
    `ID_Clasificacion` varchar(50) DEFAULT NULL,
    `FLG_Debe_Haber` int DEFAULT '0',
    `Cod_Matching` int DEFAULT '0',
    `NUM_PasoWorkflow` int DEFAULT NULL,
    `Umbral_Tolerancia` decimal(10,2) DEFAULT NULL,
    `ID_Tipo_Movimiento` int DEFAULT NULL,
    `Desc_Tipo_Movimiento` varchar(50) DEFAULT 'NORMAL',
    `Flag_No_Habilitado_Match_Unitario` int DEFAULT '0',
    `Val_Tolerancia_Ajuste_Matching` decimal(10,2) DEFAULT NULL,
    `flag_conciliado` bit(1) DEFAULT b'0',
    `ID_Cancelacion` int DEFAULT NULL,
    `TimeStamp_Creacion` datetime(3) DEFAULT NULL,
    `ID_User` int DEFAULT NULL,
    `Flag_Error` int DEFAULT '0',
    `Descr_Error` varchar(100) DEFAULT '',
    `ctrl_disable_warning` bit(1) DEFAULT b'0',
    `BData_Moneda_Num` int DEFAULT NULL,
    `BData_Moneda_Char` varchar(45) DEFAULT NULL,
    `BData_Importe_SSigno_Decimal` decimal(15,2) DEFAULT NULL,
    `BData_Importe_CSigno_Decimal` decimal(15,2) DEFAULT NULL,
    `BData_Signo_Char` varchar(45) DEFAULT NULL,
    `BData_Debito_Credito_Num` int DEFAULT NULL,
    `BData_Estatus_Movimiento_Num` int DEFAULT NULL,
    `BData_Estatus_Movimiento_Char` varchar(100) DEFAULT '',
    `BData_Tipo_Transaccion_Num` int DEFAULT NULL,
    `BData_Tipo_Transaccion_Char` varchar(45) DEFAULT NULL,
    `BData_Subtipo_Transaccion_Num` int DEFAULT NULL,
    `BData_Subtipo_Transaccion_Char` varchar(45) DEFAULT NULL,
    `BData_Identificador_Unico_Key_Num` bigint DEFAULT NULL,
    `BData_Identificador_Unico_Key_Char` varchar(100) DEFAULT NULL,
    `BData_Empresa_Num` int DEFAULT NULL,
    `BData_Empresa_Char` varchar(45) DEFAULT NULL,
    `BData_Banco_Char` varchar(100) DEFAULT NULL,
    `BData_Empresa_RUT_Num` decimal(20,0) DEFAULT NULL,
    `BData_Empresa_RUT_Char` varchar(100) DEFAULT NULL,
    `BData_Cuenta_Num` decimal(20,0) DEFAULT NULL,
    `BData_Cuenta_Char` varchar(45) DEFAULT NULL,
    `BData_Planilla_Num` int DEFAULT NULL,
    `BData_Sucursal_Num` int DEFAULT NULL,
    `BData_Sucursal_Char` varchar(100) DEFAULT NULL,
    `BData_Departamento_Num` int DEFAULT NULL,
    `BData_Departamento_Char` varchar(100) DEFAULT NULL,
    `BData_Ciudad_Char` varchar(100) CHARACTER SET big5 COLLATE big5_chinese_ci DEFAULT NULL,
    `BData_Localidad_Char` varchar(100) DEFAULT NULL,
    `BData_Sub_Localidad_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Card_Number_Decimal` decimal(45,0) DEFAULT NULL,
    `BData_Tarjet_Card_Number_PCI` varchar(45) DEFAULT NULL,
    `BData_Tarjet_Expiration_Date` varchar(4) DEFAULT NULL,
    `BData_Tarjet_Authorization_Num` bigint DEFAULT NULL,
    `BData_Tarjet_Authorization_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Cant_Cuotas` int DEFAULT NULL,
    `BData_Tarjet_Afiliado_Char` varchar(45) DEFAULT NULL,
    `BData_Tarjet_Tipo_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Marca_Char` varchar(100) DEFAULT NULL,
    `BData_Tarjet_Liquidacion_Num` int DEFAULT NULL,
    `BData_Tarjet_Cupon_Num` decimal(10,0) DEFAULT NULL,
    `BData_Nro_Comercio_Num` decimal(10,0) DEFAULT NULL,
    `BData_Nro_Terminal_Num` decimal(10,0) DEFAULT NULL,
    `BData_Fecha_Compra` date DEFAULT NULL,
    `BData_Fecha_Presentacion` date DEFAULT NULL,
    `BData_Fecha_Liquidacion` date DEFAULT NULL,
    `BData_Fecha_Proceso` date DEFAULT NULL,
    `BData_Voucher_Num` bigint DEFAULT NULL,
    `BData_File_Num` bigint DEFAULT NULL,
    `BData_Medio_Pago_Char` varchar(100) DEFAULT NULL,
    `BData_Canal_Distribucion_Char` varchar(100) DEFAULT NULL,
    `BData_Ciclo_Distribucion_Num` int DEFAULT NULL,
    `BData_Medio_Distribucion_Char` varchar(100) DEFAULT NULL,
    `BData_Ramo_Actividad_Char` varchar(100) DEFAULT NULL,
    `BData_Sector_Actividad_Char` varchar(100) DEFAULT NULL,
    `BData_Cartera_Num` int DEFAULT NULL,
    `BData_Cartera_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Nombre_Char` varchar(200) DEFAULT NULL,
    `BData_Cli_Documento_Char` varchar(45) DEFAULT NULL,
    `BData_Cli_Domicilio_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Correo_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Telefono_Char` varchar(100) DEFAULT NULL,
    `BData_Cli_Estatus_Num` int DEFAULT NULL,
    `BData_Cli_Estatus_Char` varchar(100) DEFAULT NULL,
    `BData_Cod_Articulo_Char` varchar(45) DEFAULT NULL,
    `BData_Nombre_Articulo_Char` varchar(50) DEFAULT NULL,
    `BData_Descr_Articulo_Char` varchar(100) DEFAULT NULL,
    `BData_Imp_Credito_Bruto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Debito_Bruto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Credito_Neto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Debito_Neto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Comision` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Margen` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Tasas` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Intercambio` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Bruto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Descuento` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Neto` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Total_Factura` decimal(15,2) DEFAULT NULL,
    `BData_Imp_Cashback` decimal(15,2) DEFAULT NULL,
    `VectorExtValor00` decimal(15,2) DEFAULT NULL,
    `VectorExtValor01` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor02` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor03` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor04` decimal(15,2) DEFAULT '0.00',
    `VectorExtValor05` decimal(15,2) DEFAULT NULL,
    `VectorExtValor06` decimal(15,2) DEFAULT NULL,
    `VectorExtValor07` decimal(15,2) DEFAULT NULL,
    `VectorExtValor08` decimal(15,2) DEFAULT NULL,
    `VectorExtValor09` decimal(15,2) DEFAULT NULL,
    `VectorExtValor10` decimal(15,2) DEFAULT NULL,
    `VectorExtTexto01` varchar(100) DEFAULT NULL,
    `VectorExtTexto02` varchar(100) DEFAULT NULL,
    `VectorExtTexto03` varchar(100) DEFAULT NULL,
    `VectorExtTexto04` varchar(100) DEFAULT NULL,
    `VectorExtNum01` int DEFAULT NULL,
    `VectorExtNum02` int DEFAULT NULL,
    `VectorExtNum03` int DEFAULT NULL,
    `VectorExtNum04` int DEFAULT NULL,
    `ID_Template_Formato_Archivo` int DEFAULT NULL,
    `id_sistema_origen` int DEFAULT NULL,
    `cod_sistema_origen_externo` int DEFAULT NULL,
    `Ctrl_Nombre_Archivo_Carga` varchar(200) DEFAULT NULL,
    `id_file_load` int DEFAULT NULL,
    `Ctrl_CheckSum` char(32) DEFAULT NULL,
    `id_clase_movimiento` int DEFAULT '1',
    `id_tipo_estado_partida` int DEFAULT '1',
    `id_movimiento_raiz` bigint DEFAULT NULL,
    `cardinal_descendiente_raiz` int DEFAULT NULL,
    `desc_comentario_movimiento` varchar(200) DEFAULT NULL,
    `flag_caso_asociado` int DEFAULT '0',
    `id_caso_asociado` int DEFAULT NULL,
    PRIMARY KEY (`ID_Fila_PK`),
    KEY `fk_dw_movs_contables@cancelacion_idx` (`ID_Cancelacion`),
    KEY `fk_dw_movs_contables@cuentas_idx` (`ID_Cuenta`) /*!80000 INVISIBLE */,
    KEY `INDICE_FECHA` (`Fecha_Maestra`),
    KEY `fk_dw_movs_entidad@cod_aaaamm_idx` (`Cod_AAAAMM`),
    KEY `fk_dw_movs_entidad@flg_dh_idx` (`FLG_Debe_Haber`),
    KEY `index9` (`BData_Identificador_Unico_Key_Num`),
    KEY `index10` (`cod_sistema_origen_externo`),
    KEY `Autorizacion_Char` (`BData_Tarjet_Authorization_Char`) /*!80000 INVISIBLE */,
    KEY `Autorizacion_Num` (`BData_Tarjet_Authorization_Num`),
    KEY `nro_cuenta` (`BData_Cuenta_Num`),
    KEY `checksum` (`Ctrl_CheckSum`,`Cod_AAAAMM`,`ID_Cuenta`),
    KEY `Cuenta y Periodo` (`ID_Cuenta`,`Cod_AAAAMM`,`flag_conciliado`),
    CONSTRAINT `fk_dw_movs_contables@cancelacion` FOREIGN KEY (`ID_Cancelacion`) REFERENCES `dw_cancelaciones` (`ID_Cancelacion_PK`),
    CONSTRAINT `fk_dw_movs_contables@cuentas` FOREIGN KEY (`ID_Cuenta`) REFERENCES `dw_cuentas` (`ID_Cuenta_PK`)
    ) ENGINE=InnoDB AUTO_INCREMENT=20279259 DEFAULT CHARSET=utf8mb3;

    TABLE `dw_links` (
    `ID_Link_PK` bigint NOT NULL AUTO_INCREMENT,
    `ID_Cancelacion` int DEFAULT NULL,
    `id_cliente` int DEFAULT NULL,
    `id_cuenta` int DEFAULT NULL,
    `ID_Mov_Contable` bigint DEFAULT NULL,
    `ID_Mov_Entidad` bigint DEFAULT NULL,
    `COD_AAAAMM` int DEFAULT NULL,
    PRIMARY KEY (`ID_Link_PK`),
    KEY `fk_dw_links@cancelacion_idx` (`ID_Cancelacion`),
    KEY `fk_dw_links@movcontable_idx` (`ID_Mov_Contable`),
    KEY `fk_dw_links@moventidad_idx` (`ID_Mov_Entidad`),
    CONSTRAINT `fk_dw_links@cancelacion` FOREIGN KEY (`ID_Cancelacion`) REFERENCES `dw_cancelaciones` (`ID_Cancelacion_PK`)
    ) ENGINE=InnoDB AUTO_INCREMENT=18929834 DEFAULT CHARSET=utf8mb3;

    TABLE `dw_cuentas` (
    `ID_Cuenta_PK` int NOT NULL AUTO_INCREMENT,
    `id_cliente` int DEFAULT NULL,
    `ID_Empresa` int DEFAULT '0',
    `json_sistemas_origen` varchar(200) DEFAULT NULL,
    `ID_Entidad` int DEFAULT '0',
    `ID_Moneda` int DEFAULT '0',
    `NUM_Cuenta_Empresa` varchar(50) DEFAULT NULL,
    `NUM_Cuenta_Entidad` varchar(50) DEFAULT NULL,
    `DESC_Cuenta` varchar(50) DEFAULT NULL,
    `descripcion_extendida` varchar(400) DEFAULT NULL,
    `num_orden` int DEFAULT NULL,
    `ID_User` int DEFAULT '0',
    `ID_FechaInicioActividad` int DEFAULT '0',
    `num_mes_cierre_ejercicio` int DEFAULT '12',
    `FLAG_Registro_Eliminado` int DEFAULT '0',
    `ID_Periodicidad_Conciliacion` int DEFAULT '0',
    `Saldo_Inicial_Contable` decimal(20,2) DEFAULT '0.00',
    `Saldo_Inicial_Entidad` decimal(20,2) DEFAULT '0.00',
    `flag_control_saldos` int DEFAULT '1',
    `id_tipo_control_saldos` int DEFAULT NULL,
    `id_visualizacion_historica_periodos` int DEFAULT '2',
    `flag_control_repeticiones` int DEFAULT '1',
    `flag_control_fechas` int DEFAULT '0',
    `flag_control_importes_excluyentes` int DEFAULT '0',
    `flag_control_filas_subtotales` int DEFAULT '0',
    `flag_control_nombre_archivos_repetidos_enable` int DEFAULT '0',
    `flag_habilitado` int DEFAULT '1',
    `id_tipo_cuenta` int DEFAULT '0',
    `id_tipo_carga_default` int DEFAULT '0',
    `label_contable` varchar(45) DEFAULT NULL,
    `label_entidad` varchar(45) DEFAULT NULL,
    `label_debe` varchar(45) DEFAULT NULL,
    `label_haber` varchar(45) DEFAULT NULL,
    `cant_periodos_histo_almacen_frio` int DEFAULT NULL,
    `cant_periodos_histo_eliminacion_definitiva` int DEFAULT NULL,
    `flag_periodo_previo_partidas` int DEFAULT '0',
    `flag_notificar_final_conciliacion` int DEFAULT '0',
    `json_usuarios_notificar` varchar(100) DEFAULT NULL,
    `seed_origen_id_cuenta_pk` int DEFAULT NULL,
    `id_param_match_per_ini` int DEFAULT '1',
    `param_offset_ini` int DEFAULT '0',
    `id_param_match_per_fin` int DEFAULT '1',
    `param_offset_fin` int DEFAULT '0',
    `cr_fingerprint` varchar(8) DEFAULT NULL,
    `cr_id_user` int DEFAULT NULL,
    `cr_timestamp` datetime DEFAULT NULL,
    PRIMARY KEY (`ID_Cuenta_PK`),
    KEY `fk_dw_cuentas@empresa_idx` (`ID_Empresa`),
    KEY `fk_dw_cuentas@moneda_idx` (`ID_Moneda`),
    KEY `fk_dw_cuentas@usuario_idx` (`ID_User`),
    CONSTRAINT `fk_dw_cuentas@empresa` FOREIGN KEY (`ID_Empresa`) REFERENCES `sis_empresas` (`ID_Empresa_PK`),
    CONSTRAINT `fk_dw_cuentas@moneda` FOREIGN KEY (`ID_Moneda`) REFERENCES `sis_monedas` (`ID_Moneda_PK`),
    CONSTRAINT `fk_dw_cuentas@usuario` FOREIGN KEY (`ID_User`) REFERENCES `sis_usuarios` (`ID_User_PK`)
    ) ENGINE=InnoDB AUTO_INCREMENT=969 DEFAULT CHARSET=utf8mb3;

    TABLE `dw_cancelaciones` (
    `ID_Cancelacion_PK` int NOT NULL AUTO_INCREMENT,
    `ID_TipoCancelacion` int DEFAULT NULL,
    `id_cliente` int DEFAULT NULL,
    `ID_Cuenta` int DEFAULT NULL,
    `ID_TipoMatching` int DEFAULT NULL,
    `NUM_PasoWorkflow` int DEFAULT NULL,
    `Umbral_Tolerancia` decimal(10,2) DEFAULT '0.00',
    `FLAG_CancelacionConAjuste` int DEFAULT '0',
    `Importe_Ajuste_Debe` decimal(15,2) DEFAULT '0.00',
    `Importe_Ajuste_Haber` decimal(15,2) DEFAULT '0.00',
    `Cod_AAAAMM_Ini` int DEFAULT NULL,
    `Cod_AAAAMM_Fin` int DEFAULT NULL,
    `Lista_AAAAMM` varchar(100) DEFAULT NULL,
    `FLAG_InterPeriodos` int DEFAULT '0',
    `Minima_Fecha_Contable` date DEFAULT NULL,
    `Maxima_Fecha_Contable` date DEFAULT NULL,
    `Minima_Fecha_Banco` date DEFAULT NULL,
    `Maxima_Fecha_Banco` date DEFAULT NULL,
    `TimeStamp_Creacion` datetime(3) DEFAULT NULL,
    `ID_User` int DEFAULT NULL,
    `DESC_Descripcion` varchar(1000) DEFAULT NULL,
    `ID_Registro_Lote_Proceso` bigint DEFAULT NULL,
    `id_grupo_conciliaciones` int DEFAULT NULL,
    `id_paso_datamatching` int DEFAULT NULL,
    `porc_probabilidad_matching` int DEFAULT '0',
    `txt_metadata_matching` varchar(500) DEFAULT NULL,
    `id_tipo_estado_conciliacion` int DEFAULT '1',
    `flag_caso_asociado` int DEFAULT '0',
    `id_caso_expediente` int DEFAULT NULL,
    `cant_partidas_conciliadas` int DEFAULT NULL,
    `flag_conciliacion_masiva` int DEFAULT '0',
    `id_ref_data_ext_01` int DEFAULT NULL,
    `id_ref_data_ext_02` int DEFAULT NULL,
    `cod_ref_data_ext_01` varchar(45) DEFAULT NULL,
    `cod_ref_data_ext_02` varchar(45) DEFAULT NULL,
    `json_data_ext` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`ID_Cancelacion_PK`),
    KEY `fk_dw_cancelaciones@tipomatching_idx` (`ID_TipoMatching`),
    KEY `fk_dw_cancelaciones@cuenta_idx` (`ID_Cuenta`),
    KEY `fk_dw_cancelaciones@usuario_idx` (`ID_User`),
    CONSTRAINT `fk_dw_cancelaciones@cuenta` FOREIGN KEY (`ID_Cuenta`) REFERENCES `dw_cuentas` (`ID_Cuenta_PK`),
    CONSTRAINT `fk_dw_cancelaciones@tipomatching` FOREIGN KEY (`ID_TipoMatching`) REFERENCES `sis_metodo_matching` (`ID_MetodoMatching_PK`),
    CONSTRAINT `fk_dw_cancelaciones@usuario` FOREIGN KEY (`ID_User`) REFERENCES `sis_usuarios` (`ID_User_PK`)
    ) ENGINE=InnoDB AUTO_INCREMENT=6704147 DEFAULT CHARSET=utf8mb3;
    """